### ISSUE TITLE
[Crash] incompatible with copperative in 1.19.2

### ISSUE THREAD

**Issue by AiDSl** [SuperMartijn642/RechiseledCreate#8] opened 2023-12-17 11:43 UTC
**Version Info**
Copperative 1.19.2--1.1.0.jar
rechiseledcreate-1.0.1-forge-mc1.19.jar

theoneprobe-1.19-6.2.2.jar
jei-1.19.2-forge-11.6.0.1018.jar
create-1.19.2-0.5.1.f.jar
rechiseled-1.1.5c-forge-mc1.19.2.jar

fusion-1.1.0b-forge-mc1.19.2.jar
moonlight-1.19.2-2.3.5-forge.jar
supermartijn642configlib-1.1.8-forge-mc1.19.jar
supermartijn642corelib-1.1.16-forge-mc1.19.2.jar

**Steps to Reproduce**
1.install rechiseledcreate and Copperative 
2.crash
...

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/RechiseledCreate/files/13695886/latest.log)
...

I try to make a mod pack to with both and it crashed,and I just remove almost all mod and producable with only copperative and Rechiseled: Create,but if I remove Rechiseled: Create,it works fine

and just have trouble with "Rechiseled: Create",it is fine if it removed but with rechiseled remained.

and I am using windows with ATlauncher

**Comment by SuperMartijn642** [comment] 2024-04-23 20:36
It seems the crash only occurs if Copperative, Create, and Rechiseled are installed. Looking at the issues on Copperative's repository, it seems different combinations of mods with Copperative produce a similar crash. I also can't really identify anything in Rechiseled which would be related to such an issue.
As such, I assume the issue is on Copperative's side.

As the issue is unrelated to Rechiseled: Create, I will close the issue.

**Closed as completed by SuperMartijn642** 2024-04-23 20:36 UTC
